/* ============================================================
   categories.js — Shared experiment data + category map
   Used by: main.js (homepage) and category-page.js (filtered pages)
   ============================================================ */

export const experiments = [
    {
        id: 'projectile',
        title: 'Projectile Motion',
        description: 'Launch a projectile and study parabolic trajectories under gravity. Explore how angle and velocity affect range and height.',
        icon: '🚀',
        iconClass: 'physics',
        badge: 'Basic',
        badgeClass: 'badge-beginner',
    },
    {
        id: 'pendulum',
        title: 'Pendulum Motion',
        description: 'Observe simple harmonic motion of a pendulum. Investigate the effects of length, angle, and gravity on oscillation period.',
        icon: '🕰️',
        iconClass: 'physics',
        badge: 'Basic',
        badgeClass: 'badge-beginner',
    },
    {
        id: 'wave-interference',
        title: 'Wave Interference',
        description: 'Visualize constructive and destructive interference patterns when two waves superpose. Control frequency and amplitude.',
        icon: '🌊',
        iconClass: 'waves',
        badge: 'Intermediate',
        badgeClass: 'badge-intermediate',
    },
    {
        id: 'ohms-law',
        title: "Ohm's Law Circuit",
        description: 'Build a simple circuit and explore the linear relationship between voltage, current, and resistance.',
        icon: '⚡',
        iconClass: 'circuit',
        badge: 'Basic',
        badgeClass: 'badge-beginner',
    },
    {
        id: 'refraction',
        title: 'Refraction of Light',
        description: "Trace light rays crossing a boundary between media. Observe Snell's Law and total internal reflection in action.",
        icon: '🔬',
        iconClass: 'optics',
        badge: 'Intermediate',
        badgeClass: 'badge-intermediate',
    },
    {
        id: 'momentum',
        title: 'Momentum Conservation',
        description: 'Study elastic and inelastic collisions. Analyze momentum vectors and the coefficient of restitution.',
        icon: '💥',
        iconClass: 'physics',
        badge: 'Intermediate',
        badgeClass: 'badge-intermediate',
    },
    {
        id: 'series-parallel',
        title: 'Series & Parallel Circuits',
        description: 'Build circuits with multiple resistors. Compare voltage drops and current paths in series vs parallel.',
        icon: '🔌',
        iconClass: 'circuit',
        badge: 'Advanced',
        badgeClass: 'badge-advanced',
    },
    {
        id: 'convex-lens',
        title: 'Geometric Optics — Convex Lens',
        description: 'Trace light rays through a convex lens. Explore real and virtual image formation and magnification.',
        icon: '🔭',
        iconClass: 'optics',
        badge: 'Advanced',
        badgeClass: 'badge-advanced',
    },
    {
        id: 'kinetic-energy',
        title: 'Kinetic Energy',
        description: 'Investigate how mass and velocity affect kinetic energy. See why speed squares the energy!',
        icon: '🏃',
        iconClass: 'physics',
        badge: 'Basic',
        badgeClass: 'badge-beginner',
    },
    {
        id: 'archimedes',
        title: 'Archimedes Principle',
        description: 'Submerge objects in fluid and measure buoyant force. Discover why objects sink, float, or hover.',
        icon: '⛵',
        iconClass: 'physics',
        badge: 'Intermediate',
        badgeClass: 'badge-intermediate',
    },
    {
        id: 'photoelectric',
        title: 'Photoelectric Effect',
        description: 'Shine light on metal plates to emit electrons. Explore threshold frequency and photon energy.',
        icon: '☀️',
        iconClass: 'physics',
        badge: 'Advanced',
        badgeClass: 'badge-advanced',
    },
    {
        id: 'newtons-second-law',
        title: "Newton's Second Law",
        description: 'Apply force to a mass with friction. Watch acceleration change as you balance the net forces.',
        icon: '🍎',
        iconClass: 'physics',
        badge: 'Basic',
        badgeClass: 'badge-beginner',
    },
    {
        id: 'gravity',
        title: 'Gravity Simulator',
        description: "Observe planetary orbits and gravitational attraction between masses using Newton's Universal Law.",
        icon: '🌍',
        iconClass: 'physics',
        badge: 'Advanced',
        badgeClass: 'badge-advanced',
    },
    {
        id: 'heat-flow',
        title: 'Heat Flow Rate',
        description: "Test thermal conduction across materials. Apply Fourier's Law to see how temperature and area affect heat.",
        icon: '🔥',
        iconClass: 'thermodynamics',
        badge: 'Advanced',
        badgeClass: 'badge-advanced',
    },
    {
        id: 'cart-acceleration',
        title: 'Cart Acceleration',
        description: 'Pull a cart with constant force. Analyze the resulting Speed-Time graph to calculate acceleration.',
        icon: '🛒',
        iconClass: 'physics',
        badge: 'Intermediate',
        badgeClass: 'badge-intermediate',
    },
    {
        id: 'push-vs-pull',
        title: 'Push vs Pull',
        description: 'Apply a horizontal force to a block and see static vs kinetic friction in action. Explore how mass and friction coefficient affect motion.',
        icon: '↔️',
        iconClass: 'physics',
        badge: 'Basic',
        badgeClass: 'badge-beginner',
    },
    {
        id: 'floating-vs-sinking',
        title: 'Floating vs Sinking',
        description: 'Drop an object into fluid and watch it float or sink based on density. Explore buoyancy, weight, and Archimedes\' principle.',
        icon: '🚢',
        iconClass: 'physics',
        badge: 'Basic',
        badgeClass: 'badge-beginner',
    },
    {
        id: 'shadow-length-change',
        title: 'Shadow Length',
        description: 'Watch shadows lengthen as the sun moves across the sky. Use ray geometry and similar triangles to predict shadow length.',
        icon: '🌅',
        iconClass: 'optics',
        badge: 'Basic',
        badgeClass: 'badge-beginner',
    },
    {
        id: 'friction-inclined-plane',
        title: 'Inclined Plane',
        description: 'Place a block on a ramp and adjust the angle. Discover the critical angle where static friction fails and the block starts sliding.',
        icon: '📐',
        iconClass: 'physics',
        badge: 'Basic',
        badgeClass: 'badge-beginner',
    },
    {
        id: 'shadows-penumbra',
        title: 'Shadows & Penumbra',
        description: 'Use an extended light source to cast realistic umbra and penumbra shadows. See how source size and occluder distance shape the shadow gradient.',
        icon: '🌑',
        iconClass: 'optics',
        badge: 'Basic',
        badgeClass: 'badge-beginner',
    },
    {
        id: 'doppler-moving-source-observer',
        title: 'Doppler Effect',
        description: 'Watch wavefronts compress as source moves. Hear pitch shift via WebAudio.',
        icon: '🔊',
        iconClass: 'waves',
        badge: 'Intermediate',
        badgeClass: 'badge-intermediate',
        path: 'experiments/intermediate/doppler-moving-source-observer/index.html',
    },
    {
        id: 'polarization-and-light-filters',
        title: 'Polarization & Filters',
        description: "Rotate polarizers and watch intensity obey Malus's law.",
        icon: '🔆',
        iconClass: 'optics',
        badge: 'Intermediate',
        badgeClass: 'badge-intermediate',
        path: 'experiments/intermediate/polarization-and-light-filters/index.html',
    },
    {
        id: 'pressure-vs-area-bed-of-nails',
        title: 'Pressure vs Area',
        description: 'Spread force across many nails to reduce pressure. Safe bed-of-nails demo.',
        icon: '📌',
        iconClass: 'physics',
        badge: 'Intermediate',
        badgeClass: 'badge-intermediate',
        path: 'experiments/intermediate/pressure-vs-area-bed-of-nails/index.html',
    },
    {
        id: 'work-done',
        title: 'Work Done',
        description: 'Visualize work as area under an F-x curve with constant and variable forces.',
        icon: '⚙️',
        iconClass: 'physics',
        badge: 'Intermediate',
        badgeClass: 'badge-intermediate',
        path: 'experiments/intermediate/work-done/index.html',
    },
    {
        id: 'heat-transfer-visualization',
        title: 'Heat Transfer',
        description: 'Watch heat diffuse through a 1-D rod. Drop hotspots and see Fourier conduction.',
        icon: '🌡️',
        iconClass: 'thermodynamics',
        badge: 'Intermediate',
        badgeClass: 'badge-intermediate',
        path: 'experiments/intermediate/heat-transfer-visualization/index.html',
    },
    {
        id: 'mirror-image-formation',
        title: 'Mirror Image Formation',
        description: 'Ray-trace plane, concave, and convex mirrors. See real vs virtual images.',
        icon: '🪞',
        iconClass: 'optics',
        badge: 'Intermediate',
        badgeClass: 'badge-intermediate',
        path: 'experiments/intermediate/mirror-image-formation/index.html',
    },
    {
        id: 'speed-distance-time',
        title: 'Speed = Distance / Time',
        description: 'Use a stopwatch to measure distance and time. Compare average and instantaneous speed.',
        icon: '🏎️',
        iconClass: 'physics',
        badge: 'Intermediate',
        badgeClass: 'badge-intermediate',
        path: 'experiments/intermediate/speed-distance-time/index.html',
    },
    {
        id: 'fluid-dynamics',
        title: 'Fluid Dynamics',
        description: 'Observe laminar vs turbulent flow, vortex shedding, and Reynolds number thresholds.',
        icon: '🌊',
        iconClass: 'physics',
        badge: 'Advanced',
        badgeClass: 'badge-advanced',
        path: 'experiments/advanced/fluid-dynamics/index.html',
    },
    {
        id: 'atomic-spectra',
        title: 'Atomic Spectra',
        description: 'Simulate energy level transitions, emission spectra, and thermal broadening.',
        icon: '🌈',
        iconClass: 'physics',
        badge: 'Advanced',
        badgeClass: 'badge-advanced',
        path: 'experiments/advanced/atomic-spectra/index.html',
    },
    {
        id: 'electric-field',
        title: 'Electric Field Visualization',
        description: 'Observe field lines, equipotential maps, and field magnitude for point charges.',
        icon: '⚡',
        iconClass: 'physics',
        badge: 'Advanced',
        badgeClass: 'badge-advanced',
        path: 'experiments/advanced/electric-field/index.html',
    },
    {
        id: 'magnetic-wire',
        title: 'Magnetic Field Around Wire',
        description: 'Visualize the B-field around a straight current-carrying wire or a circular loop.',
        icon: '🧲',
        iconClass: 'physics',
        badge: 'Advanced',
        badgeClass: 'badge-advanced',
        path: 'experiments/advanced/magnetic-wire/index.html',
    },
    {
        id: 'wave-speed',
        title: 'Wave Speed in Medium',
        description: 'Observe 1D/2D wave propagation, measure phase speed, and explore dispersion.',
        icon: '🌊',
        iconClass: 'waves',
        badge: 'Advanced',
        badgeClass: 'badge-advanced',
        path: 'experiments/advanced/wave-speed/index.html',
    },
];

/**
 * Category definitions — grouped experiment IDs by difficulty level.
 * badgeClass must match an existing .badge-* class in index.css.
 */
export const CATEGORIES = {
    basic: {
        label: 'Basic',
        badgeClass: 'badge-beginner',
        description: 'Foundational simulations covering motion, circuits, and energy — ideal starting points for exploring physics.',
        ids: ['projectile', 'pendulum', 'ohms-law', 'newtons-second-law', 'kinetic-energy',
              'push-vs-pull', 'floating-vs-sinking', 'shadow-length-change',
              'friction-inclined-plane', 'shadows-penumbra'],
    },
    intermediate: {
        label: 'Intermediate',
        badgeClass: 'badge-intermediate',
        description: 'Mid-level simulations covering waves, optics, momentum, buoyancy, and kinematics.',
        ids: ['wave-interference', 'refraction', 'momentum', 'archimedes', 'cart-acceleration',
              'doppler-moving-source-observer', 'polarization-and-light-filters',
              'pressure-vs-area-bed-of-nails', 'work-done', 'heat-transfer-visualization',
              'mirror-image-formation', 'speed-distance-time'],
    },
    advanced: {
        label: 'Advanced',
        badgeClass: 'badge-advanced',
        description: 'Ten advanced simulations exploring circuits, optics, quantum effects, gravity, thermodynamics, and electromagnetism.',
        ids: ['series-parallel', 'convex-lens', 'photoelectric', 'gravity', 'heat-flow', 'fluid-dynamics', 'atomic-spectra', 'electric-field', 'magnetic-wire', 'wave-speed'],
    },
};

/**
 * Returns the 5 experiment objects for a given category key.
 * @param {'basic'|'intermediate'|'advanced'} key
 * @returns {Array}
 */
export function experimentsByCategory(key) {
    const cat = CATEGORIES[key];
    if (!cat) return [];
    return cat.ids.map(id => experiments.find(e => e.id === id)).filter(Boolean);
}
